feat: Profile
BP-WiSe21-22-Gruppe-52/BP-frontend pull request #101
Opened 2022-01-14 17:31 UTC by Laennart

Implementation is mostly missing because it depends on other branches. This should be a separate task.

Closes #88

2022-01-14 23:47 UTC, Gamer92000 commented on src/pages/profile.tsx
> +    "https://cdn.geoscribble.de/avatars/avatar_1.png"
maybe don't hardcode this?

2022-01-14 23:47 UTC, Gamer92000 commented on src/pages/profile.tsx
> +  const dailyRating = 4; // TODO
TODO in merge to main?

2022-01-14 23:47 UTC, Gamer92000 commented on src/pages/profile.tsx
> +                    marginTop: "30px",
I think this margin breaks the animation, maybe move to ReactCardFlip or a wrapper around that instead?

2022-01-14 23:47 UTC, Gamer92000 commented on src/pages/profile.tsx
> +                    />
Maybe make the icon part of the button?

2022-01-15 13:46 UTC, Laennart commented on src/pages/profile.tsx
> +  const dailyRating = 4; // TODO
As I wrote in the PR description, there are many TODO items but they rely on logic added in other branches. We can wait until everything is merged and finalize the profile or merge this and have the initial design ready.

2022-01-18 17:52 UTC, Gamer92000 requested changes

2022-01-18 17:52 UTC, Gamer92000 commented on src/locales/de/translation.json
> +    "edit": "Bearbeiten \uD83D\uDD8B",
Please don't actually use this unicode pen.
The ant icon could be good(?)

2022-01-18 17:52 UTC, Gamer92000 commented on src/util/exercise_cache.ts
> +export default ExerciseCache;
Please use the redux store specifically designed for this kind of stuff.

2022-01-18 17:52 UTC, Gamer92000 commented on src/pages/profile/profile.tsx
> +import React, { useEffect } from "react";
Consider renaming this file to `index.tsx`, so you can use profile as a module and import it via `src/pages/profile` again.
Maybe also split this file into multiple for readability and keep them in the same profile folder.

2022-01-18 17:52 UTC, Gamer92000 commented on src/pages/profile/profile.tsx
> +const copyProfileData = (
rename to mergeProfileData?

2022-01-18 17:52 UTC, Gamer92000 commented on src/pages/profile/profile.tsx
> +  }
```suggestion
  const avatarIds: number[] = [...Array(50).keys()];
```

2022-01-18 17:52 UTC, Gamer92000 commented on src/pages/profile/profile.tsx
> +      loadProfile().catch(console.error);
Error handling in the console doesn't seem right

2022-01-18 17:52 UTC, Gamer92000 commented on src/pages/profile/profile.tsx
> +    // TODO
I still dislike TODOs :P

2022-01-18 17:52 UTC, Gamer92000 commented on src/pages/profile/profile.tsx
> +                        overlayStyle={{ width: "370px" }}
Looks not too nice for me
![image](https://user-images.githubusercontent.com/42619277/149991258-7af0e52e-942e-4698-afdb-cc6e2571f234.png)

2022-01-18 17:52 UTC, Gamer92000 commented on src/pages/exercises.tsx
>        const exercise = exerciseList[i];
```suggestion
    for (const exercise of exerciseList) {
```

2022-01-21 20:39 UTC, Gamer92000 requested changes
I'm sorry

2022-01-21 20:39 UTC, Gamer92000 commented on src/pages/profile/index.tsx
> +      avatarId: profile.data.avatar,
Avatar ID 0 is default but does not exist :(
![image](https://user-images.githubusercontent.com/42619277/150596774-c14e55d9-52c9-4fe6-ba25-bcce063da91c.png)

2022-01-21 20:39 UTC, Gamer92000 commented on src/util/api.ts
> +  serverUrl = "http://78.46.150.116:9000/";
Why is this pushed?
```suggestion
  serverUrl = "http://78.46.150.116:8000/";
```

2022-01-22 14:46 UTC, Gamer92000 commented on src/util/helper.ts
> +  },
Please also use this for `isFuture` and `isPast` in `src/pages/exercises.tsx`.

2022-01-24 09:02 UTC, Laennart commented on src/pages/profile/index.tsx
> +      avatarId: profile.data.avatar,
This is a backend issue. I think we should include an avatar selection into the registration process. This would be a task for the login/register redesign. 
CC @Y4nnikH

2022-01-24 09:10 UTC, Y4nnikH commented on src/pages/profile/index.tsx
> +      avatarId: profile.data.avatar,
Couldn't we just add an image for an "empty" profile picture? Similar to messengers like Whatsapp etc.
I think that would be the easiest and cleanest solution

2022-01-24 09:16 UTC, Laennart commented on src/pages/profile/index.tsx
> +      avatarId: profile.data.avatar,
Sure, that would be possible.

2022-02-09 18:05 UTC, Gamer92000 approved these changes

2022-02-09 18:16 UTC, Y4nnikH requested changes
Please change the cursor to pointer when hovering over a clickable object

2022-02-12 16:51 UTC, Gamer92000 approved these changes

2022-02-14 17:59 UTC, Y4nnikH approved these changes
Nice buttons very nice!

2022-02-14 18:01 UTC, merged