Feat/train - review pwease
BP-WiSe21-22-Gruppe-52/BP-frontend pull request #115
Opened 2022-01-21 12:26 UTC by Y4nnikH

2022-01-22 15:06 UTC, Gamer92000 requested changes
Didn't you want to rework the train style?

2022-01-22 15:06 UTC, Gamer92000 commented on src/pages/train.tsx
> +      />
![image](https://user-images.githubusercontent.com/42619277/150643762-bde4a8ca-3475-4e51-9ead-eb67da1fa149.png)
Maybe add some max dimensions to this? Or even better dynamic scaling

2022-01-22 15:06 UTC, Gamer92000 commented on src/pages/train.tsx
> +                exercise && exercise.description
What happened to the paper visualization?

2022-01-22 15:06 UTC, Gamer92000 commented on src/pages/train.tsx
> +  // 0: not yet loading, 1: currently fetching data from api, 2: finished loading
```suggestion
```

2022-01-22 15:06 UTC, Gamer92000 commented on src/pages/train.tsx
> +  const [progress /*, setProgress*/] = useState(10);
Can't this be real data?

2022-01-22 15:06 UTC, Gamer92000 commented on src/styles/home.css
> +}
Could you double check that this doesn't break other progress bars?

2022-01-22 15:06 UTC, Gamer92000 commented on src/util/api.ts
> +    console.log(this.ws);
```suggestion
```

2022-01-23 13:45 UTC, Y4nnikH commented on src/pages/train.tsx
> +                exercise && exercise.description
Paper is bad for the environment

2022-01-23 13:49 UTC, Y4nnikH commented on src/pages/train.tsx
> +  const [progress /*, setProgress*/] = useState(10);
Not really, because the bar is supposed to show the progress in terms of completed sets, which is not yet implemented in either back or front-end.

2022-01-23 13:59 UTC, Y4nnikH commented on src/pages/train.tsx
> +                exercise && exercise.description
(belongs within the scope of user story 38)

2022-01-23 14:01 UTC, Y4nnikH commented on src/styles/home.css
> +}
Seems to be fine 👍

2022-01-23 14:05 UTC, Y4nnikH commented
> Didn't you want to rework the train style?

_We_ want to rework the train style. But for now I only want the mentioned user stories to be cover in this review.

2022-02-05 11:28 UTC, Laennart requested changes
Please scale down the pin.png file as we don't need that much detail for a small pin.

2022-02-09 15:15 UTC, Y4nnikH commented on src/pages/train.tsx
> +      />
@Gamer92000 did you fix this?

2022-02-09 18:06 UTC, Gamer92000 approved these changes

2022-02-09 18:08 UTC, Laennart approved these changes
👍🏻

2022-02-14 18:12 UTC, merged