Feat/new home
BP-WiSe21-22-Gruppe-52/BP-frontend pull request #116
Opened 2022-01-21 12:59 UTC by Y4nnikH

Should be fine to merge this

2022-01-22 14:48 UTC, Gamer92000 commented on src/pages/exercises.tsx
> +              padding: "00px",
```suggestion
              padding: "0px",
```

2022-01-22 14:48 UTC, Gamer92000 commented on src/pages/exercises.tsx
> +                  // width: "100%",
```suggestion
```

2022-01-22 14:51 UTC, Gamer92000 requested changes

2022-01-22 14:51 UTC, Gamer92000 commented on src/pages/exercises.tsx
> +              padding: "00px",
```suggestion
              padding: "0px",
```

2022-01-22 14:51 UTC, Gamer92000 commented on src/pages/exercises.tsx
> +                  // width: "100%",
```suggestion
```

2022-01-22 14:51 UTC, Gamer92000 commented on src/styles/home.css
> +}
Did you double check that this doesn't break other progress bars?

2022-01-22 14:52 UTC, Y4nnikH commented on src/styles/home.css
> +}
no

2022-01-23 13:27 UTC, Y4nnikH commented on src/styles/home.css
> +}
The other ones don't seem to be affected by this 👍

2022-01-26 13:53 UTC, Gamer92000 approved these changes

2022-01-26 13:54 UTC, merged