feat: add medals to exercise done
BP-WiSe21-22-Gruppe-52/BP-frontend pull request #148
Opened 2022-02-15 19:17 UTC by Gamer92000

2022-02-15 21:27 UTC, Laennart requested changes
Works nicely! Just two minor suggestions for improvement! :)

2022-02-15 21:27 UTC, Laennart commented on src/locales/de/translation.json
> +    "medal": "Hier könnte deine Medaille stehen!",
A little suggestion for this message: (To make it more gamified)
```suggestion
    "medal": "Leider hast du dieses Mal keine Medaille verdient!",
```

2022-02-15 21:27 UTC, Laennart commented on src/locales/en/translation.json
> +    "medal": "Here could be your medal!",
```suggestion
    "medal": "Sadly you did not earn a medal this time!",
```

2022-02-15 22:48 UTC, Laennart approved these changes
🏅

2022-02-16 10:59 UTC, Laennart approved these changes

2022-02-16 11:17 UTC, Y4nnikH approved these changes
Looking good!

2022-02-16 11:18 UTC, merged