refactor: remove a lot of useless api calls by fixing useEffect calls
BP-WiSe21-22-Gruppe-52/BP-frontend pull request #193
Opened 2022-02-28 18:42 UTC by Gamer92000

2022-02-28 21:17 UTC, Laennart requested changes
Some bugs I noticed:
- I'm not able to create a new plan, the page does not load.
- Progress Bar on Training Page instantly jumps to 100% when starting the first set. On the second set it works somehow
- Countdown on setDone Page does not work

2022-02-28 21:17 UTC, Laennart commented on src/pages/manage/users/activeTrainerTable.tsx
> +    Promise.all([fetchUsers()]).then(([users]) => {
```suggestion
    fetchUsers().then((users) => {
```

2022-02-28 21:17 UTC, Laennart commented on src/pages/manage/users/invitedUserTable.tsx
> +    Promise.all([fetchUsers()]).then(([users]) => {
```suggestion
    fetchUsers().then((users) => {
```

2022-02-28 21:17 UTC, Laennart commented on src/pages/train/index.tsx
> +interface TrainProps {
```suggestion
interface trainProps {
```

2022-02-28 21:17 UTC, Laennart commented on src/pages/train/index.tsx
> +const Train: React.FC<TrainProps> = ({ rawExercise }) => {
```suggestion
const Train: React.FC<trainProps> = ({ rawExercise }) => {
```

2022-02-28 21:17 UTC, Laennart commented on src/pages/train/index.tsx
> +          "https://vid.pr0gramm.com/2021/12/28/130aaef3ab9c207a.mp4",
I think we also can remove this video 😄

2022-02-28 21:17 UTC, Laennart commented on src/pages/train/index.tsx
> +      {isLoading || exercise === null ? (
Wouldn't that also work?
```suggestion
      {isLoading || !exercise ? (
```

2022-02-28 21:17 UTC, Laennart commented on src/pages/train/index.tsx
> +              loadingExercise={false}
If this property is always false you can remove it. (Same with `error` below)

2022-02-28 21:39 UTC, Gamer92000 commented on src/pages/train/index.tsx
> +interface TrainProps {
Nope, according to most style guides interfaces in TS should be in PascalCase.
E.g. see https://dirask.com/posts/TypeScript-interface-naming-convention-x1RwqD

2022-02-28 21:47 UTC, Laennart commented on src/pages/train/index.tsx
> +interface TrainProps {
In your previous refactoring PRs you changed everything to lower case 🤔 
E.g. [here](https://github.com/BP-WiSe21-22-Gruppe-52/BP-frontend/blob/07b34fdaf05b1aeb6fcb490fb01c05f018c082ed/src/pages/train/setDone.tsx#L16)

2022-02-28 22:09 UTC, Gamer92000 commented on src/pages/train/index.tsx
> +interface TrainProps {
Hmmm 🤔 
Past errors shall not dictate future misconduct.

2022-03-01 15:13 UTC, Laennart approved these changes
🔧

2022-03-01 15:13 UTC, merged